---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pr0d1r2/nix-lefthook-ci-action@311740298599dab21f2dc0f83f1d8c974215d197

  build-linux-arm:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pr0d1r2/nix-lefthook-ci-action@311740298599dab21f2dc0f83f1d8c974215d197
        with:
          extra-platforms: aarch64-linux

  build-macos:
    needs: build-linux-arm
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pr0d1r2/nix-lefthook-ci-action@311740298599dab21f2dc0f83f1d8c974215d197
